### ISSUE TITLE
How to set up UDP protocol

### ISSUE THREAD

**Issue by dcafarelli** [openbaton/go-docker-vnfm#8]
Hello, 
I have installed the docker image on OpenBaton following the procedure VNF Package - NSDescriptot ecc..

My issue is that in my json file contained in the VNF Package I don't know how to set up UDP as protocol. 
If in the ConfigurationParameters under the voice "publish" I don't specify anything (ex: 5683:5683) it returns "tcp" as protocol, but if I specify "udp" it gives me a strconv error.

Thank you

**Comment by ranzpirat** [comment]
Hey,

your configuration parameter should look like this:

```json 
{
  "confKey":"publish",
  "value":"5683:5683/udp"
}
```
If this is already the case or you get the same/another error with it please provide the logs of nfvo/vnfm-docker/plugin-vimdriver-docker.

Best regards

**Comment by dcafarelli** [comment]
Hi,
thanks for your answer. I've already tried with the piece of code you suggested.
This is the errore I get when I launch the NSDescriptor:
`ERROR:strconv.ParseUint: parsing "5683/udp": invalid syntax`

What should I do to make it work?

**Comment by ranzpirat** [comment]
FYI: Unfortunately I am not able to work/debug on this today. I will come back to this issue as soon as its possible for me tomorrow.

**Comment by dcafarelli** [comment]
I'd really appreciate it.

Thank you

**Comment by dcafarelli** [comment]
Hi, I've got the 6.0.1 version of OpenBaton but, when I repeat the same procedure I explained above  (specifically when I launch the NSD) I got the NULL state. 

I've also tried with the MongoDB example but I got the same NULL state.

How can I fix it?
Thank you

**Comment by ranzpirat** [comment]
Hey caff93, sorry for the long delay; I had troubles getting my setup to work again as well. Please try again using "latest" tag with the nfvo/vnfm/plugin. It seems there was a minor parsing problem in the vnfm and also not the lastest code pushed to docker hub.

If the problem persists try building the NFVO and vnfm-docker localy and use these. If this fixes it please tell me so I can audit our build pipeline.

**Comment by dcafarelli** [comment]
Now It works just fine.

Thank you!
